### ISSUE TITLE
Python: support custom decorators

### ISSUE THREAD

**Issue by nomorepanic** [muukii/jackhammer-syntax#1]
Hi there! I am enjoying the theme, especially because fits nicely with seti ui. 
In Python, only standard decorators are highlighted, while custom defined ones are not.

Highlighted:
```
@staticmethod
@classmethod
```

Not highlighted:
```
@mydecorator
@pytest.fixture
```

**Comment by muukii** [comment]
@Vesuvium 
Thank you for the proposal.
But, I don't know how to add syntax rules.
Can you create PR?

**Comment by nomorepanic** [comment]
I see, as soon as I have some time :)

**Comment by nomorepanic** [comment]
Atom does not make a clear distinction, so it's only possible to color the entire row on custom decorators. This would overwrite the "@" color on standard decorators, and within jackhammer it does not looks nice.
